//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Asset.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class AssetDeclaration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetDeclaration()
        {
            this.AssetDetails = new HashSet<AssetDetail>();
        }
    
        public int AssetId { get; set; }

        [Required]
        [Remote("IsUserExists", "AssetDeclaration", ErrorMessage = "AssertType value already  exist - Please Provide a New Input")]
        public string AssertType { get; set; }

        [Required]
        [Remote("IsPrefixExists", "AssetDeclaration", ErrorMessage = "AssertPrefix value already  exist - Please Provide a New Input")]
        public string AssertPrefix { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetDetail> AssetDetails { get; set; }
    }
}
