//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Asset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultipleAttachment
    {
        public int serialNO { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string Attachments { get; set; }
    
        public virtual AssetDetail AssetDetail { get; set; }
    }
}
