//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Asset.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.UserAssets = new HashSet<UserAsset>();
        }
    
        public int UserEntryId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CorpId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmailAddress { get; set; }
        public string ReportingTo { get; set; }
        public string IsActive { get; set; }
        public string Remarks { get; set; }

        [NotMapped]
        public string FullName { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAsset> UserAssets { get; set; }
    }
}
